
//import com.mysql.cj.Session;
import java.awt.FlowLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.PasswordAuthentication;

import java.util.Properties;
import javax.mail.Authenticator;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ernest
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosed(e);

                //Confirmation Panel
                JPanel confirmPanel = new JPanel();
                confirmPanel.add(new JLabel("Do you want to save your changes?"));
                int selectedOption = JOptionPane.showConfirmDialog(null, confirmPanel, "File",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE);
                if (selectedOption == 0) {
                    System.out.println("Saving Emails...");
                    SaveEmails();
                } else {
                    System.out.println("Closing Program...");

                }
            }

        });
    }

    public void SaveEmails() {

        try {
            Email.SaveEmails(emails);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailContentField = new javax.swing.JTextField();
        emailTargetField = new javax.swing.JTextField();
        companyNameField = new javax.swing.JTextField();
        myNameField = new javax.swing.JTextField();
        jobTitleField = new javax.swing.JTextField();
        confirmationButton = new javax.swing.JButton();
        consoleLog = new javax.swing.JLabel();
        sendEmailTestButton = new javax.swing.JButton();
        subjectLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email Responder");

        emailContentField.setText("Your Message Here");
        emailContentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailContentFieldActionPerformed(evt);
            }
        });

        emailTargetField.setText("Blarbaman@gmail.com");
        emailTargetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTargetFieldActionPerformed(evt);
            }
        });

        companyNameField.setText("Company Name");
        companyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameFieldActionPerformed(evt);
            }
        });

        myNameField.setText("My Name");
        myNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNameFieldActionPerformed(evt);
            }
        });

        jobTitleField.setText("Job Title");

        confirmationButton.setText("Confirm Email");
        confirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationButtonActionPerformed(evt);
            }
        });

        consoleLog.setText("Info:");

        sendEmailTestButton.setText("TEST SEND AN EMAIL");
        sendEmailTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailTestButtonActionPerformed(evt);
            }
        });

        subjectLabel.setText("Subject Label            ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Target Email Address:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Company Name:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Your Name:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Job Title:");

        jButton1.setText("Preview / Edit Previous Emails");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(453, 453, 453))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consoleLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subjectLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(emailTargetField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1))
                                        .addComponent(emailContentField, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmationButton)
                                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(myNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jobTitleField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sendEmailTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(subjectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailContentField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTargetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jobTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(myNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendEmailTestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(consoleLog)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailContentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailContentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailContentFieldActionPerformed

    private void emailTargetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTargetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTargetFieldActionPerformed

    private void myNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myNameFieldActionPerformed

    private void confirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationButtonActionPerformed
        // TODO add your handling code here:
        Email e = new Email();
        e.companyName = companyNameField.getText();
        e.content = emailContentField.getText();
        e.targetEmail = emailTargetField.getText();
        e.jobTitle = jobTitleField.getText();
        e.myName = myNameField.getText();

        emails.add(e);
        this.SaveEmails();
    }//GEN-LAST:event_confirmationButtonActionPerformed

    private void sendEmailTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailTestButtonActionPerformed
        // TODO add your handling code here:
        Email e = new Email();
        e.companyName = companyNameField.getText();
        e.content = emailContentField.getText();
        e.targetEmail = emailTargetField.getText();
        e.jobTitle = jobTitleField.getText();
        e.myName = myNameField.getText();
        this.SendEmail(e);
    }//GEN-LAST:event_sendEmailTestButtonActionPerformed

    private void companyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameFieldActionPerformed
        // TODO add your handling code here:
        this.subjectLabel.setText(Email.subjectFormality + this.companyNameField.getText() + ",");
    }//GEN-LAST:event_companyNameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        NewJFrame mainFrame = this;

        if (editEmailsReady && emails.size() > 0) {

            editEmailsReady = false;

            //New Frame
            JFrame newFrame = new JFrame("Saved Emails");
            newFrame.setName("Saved Emails");
            newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            newFrame.setSize(300, 200);
            newFrame.setLocationRelativeTo(null);
            newFrame.setVisible(true);
            newFrame.setLayout(new FlowLayout(FlowLayout.LEFT));

            newFrame.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosed(WindowEvent e) {
                    editEmailsReady = true;
                }

            });
            int index = 0;
            for (Email email : this.emails) {
                //Panel
                JPanel p = new JPanel();
                //Label
                JLabel newLabel = new JLabel();
                newLabel.setText(email.companyName + ": " + email.jobTitle);

                //Delete Button
                JButton b = new JButton("Delete");
                JButton editButton = new JButton("Edit");

                //action listener for delete button
                b.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        //Confirmation Panel
                        JPanel confirmPanel = new JPanel();
                        confirmPanel.add(new JLabel("Are you sure you want to delete " + email.companyName + "'s " + email.jobTitle + " position follow up email?"));
                        int selectedOption = JOptionPane.showConfirmDialog(null, confirmPanel, "File",
                                JOptionPane.YES_NO_CANCEL_OPTION,
                                JOptionPane.PLAIN_MESSAGE);
                        if (selectedOption == 0) {
                            emails.remove(email);
                            p.remove(b);
                            p.remove(newLabel);
                            p.remove(editButton);
                            newFrame.revalidate();
                            newFrame.repaint();
                            System.out.println("Removed: " + email.toString());
                            consoleLog.setText("Removed: " + email.toString());
                        }
                    }
                });

                //edit button action listener
                editButton.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        editEmailForm editForm = new editEmailForm(email);
                        editForm.setVisible(true);

                        editForm.addWindowListener(new WindowAdapter() {
                            @Override
                            public void windowClosed(WindowEvent e) {
                                if (editForm.confirmed) {
                                    System.out.println("Adjusted email");
                                    email.companyName = editForm.getEmail().companyName;
                                    email.jobTitle = editForm.getEmail().jobTitle;
                                    email.myName = editForm.getEmail().myName;
                                    email.targetEmail = editForm.getEmail().targetEmail;
                                    email.content = editForm.getEmail().content;
                                }
                            }

                        });

                        newFrame.dispose();
                        System.out.println("Editing: " + email.toString());
                    }
                });
                //Add it all together and refresh
                p.add(newLabel);
                p.add(b);
                p.add(editButton);
                newFrame.add(p);
                newFrame.revalidate();
                newFrame.repaint();
                index++;
            }
            newFrame.pack();
            newFrame.revalidate();
            newFrame.repaint();
        } else {
            if (this.emails.size() <= 0) {
                System.out.println("No saved emails to edit or delete");
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame frame = new NewJFrame();
                frame.setVisible(true);

                //Set the subject label
                frame.subjectLabel.setText(Email.subjectFormality + frame.companyNameField.getText() + ",");

                //Load in the saved emails
                try {
                    frame.emails = Email.GetEmails();
                    frame.consoleLog.setText("Loaded " + frame.emails.size() + " emails");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public LinkedList<Email> emails = new LinkedList<>();
    public String myEmail = "Blarbaman@gmail.com";
    public boolean editEmailsReady = true;

    public void LoadEmail(Email email) {
        this.companyNameField.setText(email.companyName);
        this.emailContentField.setText(email.content);
        this.jobTitleField.setText(email.jobTitle);
        this.myNameField.setText(email.myName);
        this.emailTargetField.setText(email.targetEmail);
        this.repaint();
        this.revalidate();
    }

    //Sends an Email
    public void SendEmail(Email email) {

        // Recipient's email ID needs to be mentioned.
        String to = email.targetEmail;

        // Sender's email ID needs to be mentioned
        String from = myEmail;

        // Assuming you are sending email from through gmails smtp
        String host = "smtp.gmail.com";

        // Get system properties
        Properties properties = System.getProperties();

        // Setup mail server
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("Blarbaman@gmail.com", "Blarbaman123");  //pass your email id and password here

            }
        });

        // Used to debug SMTP issues
        session.setDebug(true);

        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            // Set Subject: header field
            message.setSubject(this.myNameField.getText() + " following up with the " + email.jobTitle + " position");

            // Now set the actual message
            message.setText(email.content);

            System.out.println("sending...");
            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyNameField;
    private javax.swing.JButton confirmationButton;
    private javax.swing.JLabel consoleLog;
    private javax.swing.JTextField emailContentField;
    private javax.swing.JTextField emailTargetField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jobTitleField;
    private javax.swing.JTextField myNameField;
    private javax.swing.JButton sendEmailTestButton;
    private javax.swing.JLabel subjectLabel;
    // End of variables declaration//GEN-END:variables
}
